/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'peter' at '1/7/17 8:36 PM' with Gradle 2.14.1
 *
 * @author peter, @date 1/7/17 8:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
